PBL3-Organizations/RUOK_Workers

.idea/appInsightsSettings.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ruok_workers/DashboardActivity.kt
app/src/main/java/com/example/ruok_workers/LoginActivity.kt
app/src/main/java/com/example/ruok_workers/RegisterActivity.kt
app/src/main/res/layout/activity_dashboard.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_register.xml

only activity

---

app/src/main/java/com/example/ruok_workers/LogoutFragment.kt

logout rendering

---

app/src/main/java/com/example/ruok_workers/Dashboard.kt
app/src/main/java/com/example/ruok_workers/DashboardAdapter.kt
app/src/main/java/com/example/ruok_workers/DashboardFragment.kt
app/src/main/res/layout/fragment_dashboard.xml

접근 여부 초기화 버튼 추가 (기능은 없이 xml만)
대시보드 노숙인 즐겨찾기 목록 더미데이터 넣어서 가시화
누르면 ProfileDetailFragment 넘어감

dashboard profile + reset button

---

.idea/deploymentTargetSelector.xml
app/src/main/java/com/example/ruok_workers/FaviconAdapter.kt
app/src/main/java/com/example/ruok_workers/FaviconFragment.kt
app/src/main/java/com/example/ruok_workers/FaviconItem.kt
app/src/main/res/layout/fragment_favicon.xml

#37 
FaviconFragment.kt 수정
fragment_favicon.xml 수정
FaviconAdaptter.kt 생성
FaviconItem.kt 생성

즐겨찾기 실기능 테스트

---

app/src/main/res/layout/fragment_location_add.xml
app/src/main/res/layout/fragment_location_revision.xml

상담내역 작성 -> 만난 위치
상담내역 수정 -> 만난 위치
xml 완료하였습니다!

Location add & revision xml

---

app/src/main/java/com/example/ruok_workers/MainActivity.kt

데이터 삽입 테스트용 코드 삭제
(샘플데이터 삽입을 위한 준비로, 테스트 코드가 있으면 충돌이 발생하여 해당 코드 삭제하였습니다)

데이터 삽입 테스트 충돌 제거

---

app/src/main/java/com/example/ruok_workers/DBManager.kt

기존 DB 스키마에 오류가 있어서 DBManage.kt에 bookmark 테이블 생성하는 코드 추가함

DB 스키마 수정-bookmark 테이블 추가

---

.idea/.name
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ruok_workers/CountingDetailAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingDetailCard.kt
app/src/main/java/com/example/ruok_workers/CountingDetailItem.kt
app/src/main/java/com/example/ruok_workers/CountingListAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingListCard.kt
app/src/main/java/com/example/ruok_workers/CountingListItem.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionCard.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionItem.kt
app/src/main/java/com/example/ruok_workers/CountingTableAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingTableCard.kt
app/src/main/java/com/example/ruok_workers/CountingTableItem.kt
app/src/main/java/com/example/ruok_workers/DashboardFragment.kt
app/src/main/java/com/example/ruok_workers/FaviconAdapter.kt
app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/java/com/example/ruok_workers/LocationTrackingFragment.kt
app/src/main/java/com/example/ruok_workers/SearchFragment.kt
app/src/main/res/layout/favicon_edit_items.xml
app/src/main/res/layout/favicon_items.xml

card -> item 이름 변경
카운팅 테이블 어댑터 연결 (기능 작업 중...)
위치 API 마커 안 뜨는 오류 수정 (애뮬레이터가 현재 위치를 미국으로 잡아서 보이지 않았던 것이었습니다... 로그로 위도 경도 찍히는 것 확인했습니다!)
노숙인 목록&검색에서 프로필 상세로 렌더링 구현
노숙인 검색하지 않으면 모든 노숙인 목록 열람 구현

location, counting adapter, search

---

app/src/main/java/com/example/ruok_workers/BriefingAddFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingAfterFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingBeforeFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingDuringFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/CheckPwFragment.kt
app/src/main/java/com/example/ruok_workers/CountingAddFragment.kt
app/src/main/java/com/example/ruok_workers/CountingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/CountingListFragment.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/CountingTableFragment.kt
app/src/main/java/com/example/ruok_workers/DashboardFragment.kt
app/src/main/java/com/example/ruok_workers/DetailsFragment.kt

B~D로 시작하는 fragment, activity에 DB 객체 생성했습니다
(DB를 사용하지 않는 fragment 및 activity에는 객체 생성하지 않았습니다)

B to D frangment와 activity에 DBManager 연동 추가

---

app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/java/com/example/ruok_workers/LocationRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/LocationTrackingFragment.kt
app/src/main/res/layout/fragment_location_add.xml
app/src/main/res/layout/fragment_location_revision.xml

location add & revision

---

app/src/main/java/com/example/ruok_workers/BriefingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/CountingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/InfoRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/ListFragment.kt
app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/java/com/example/ruok_workers/LoginActivity.kt
app/src/main/java/com/example/ruok_workers/PhotoRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/ProfileAddFragment.kt
app/src/main/java/com/example/ruok_workers/ProfileDetailFragment.kt
app/src/main/java/com/example/ruok_workers/ProfileRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/RegisterActivity.kt
app/src/main/java/com/example/ruok_workers/RevisionFragment.kt
app/src/main/java/com/example/ruok_workers/SearchFragment.kt
app/src/main/java/com/example/ruok_workers/UnknownHomelessFragment.kt

DB 객체 생성(F to U)

---

app/src/main/java/com/example/ruok_workers/RegisterActivity.kt

회원가입에서 아이디 중복체크부분 구현완료했습니다!
기존 더미데이터는 삭제하였습니다.

회원가입 아이디 중복체크 구현

---

app/src/main/java/com/example/ruok_workers/CheckPwFragment.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_check_pw.xml

비밀번호 체크 DB와 연동하여 구현했습니다!
(추가로 비밀번호 입력란에 에디트텍스트 박스와 글자 사이에 padding도 추가했습니다)

회원정보 수정 시 비밀번호 체크 DB 연동

---

app/src/main/java/com/example/ruok_workers/CheckPwFragment.kt
app/src/main/java/com/example/ruok_workers/DashboardFragment.kt
app/src/main/java/com/example/ruok_workers/InfoRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/LogoutFragment.kt
app/src/main/res/layout/fragment_info_revision.xml

회원정보 수정 부분 DB 연동 구현했습니다!
(회원 탈퇴는 아직입니다)

회원정보 수정 DB 연동

---

app/src/main/java/com/example/ruok_workers/InfoRevisionFragment.kt

회원탈퇴 DB 연동

---

app/src/main/java/com/example/ruok_workers/DashboardAdapter.kt

대시보드 노숙인 즐겨찾기 항목 클릭하면
노숙인 프로필 보기도 넘어가는 플로우 렌더링 완료했습니다!

대시보드 to 노숙인 프로필보기 구현

---

app/src/main/java/com/example/ruok_workers/CountingAddFragment.kt
app/src/main/java/com/example/ruok_workers/CountingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/CountingTableAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingTableFragment.kt
app/src/main/java/com/example/ruok_workers/CountingTableItem.kt
app/src/main/java/com/example/ruok_workers/FaviconAdapter.kt
app/src/main/java/com/example/ruok_workers/FaviconItem.kt
app/src/main/java/com/example/ruok_workers/HomelessListAdapter.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/SearchFragment.kt
app/src/main/res/layout/counting_table_items.xml
app/src/main/res/layout/favicon_edit_items.xml
app/src/main/res/layout/fragment_counting_add.xml
app/src/main/res/layout/fragment_counting_table.xml

노숙인 검색 & 목록
-> 위 부분 손대다가 같은 아이템 사용하는 상담 내역 작성의 노숙인 검색 부분도 작업하게 됨
카운팅은 아직 미완인데 위 부분 때문에 PR 보냅니다.

search & homelesslist

---

app/src/main/java/com/example/ruok_workers/ConsultationItem.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/PhotoAddFragment.kt

PhotoAddFragmentd에서 사진파일 내부저장소에 저장 후
HomelessListFragment로 사진파일명 전달하는 부분 구현했습니다!

상담내역 PhotoAddFragment에서 HomelessListFragment로 데이터 전달

---

app/src/main/java/com/example/ruok_workers/ConsultationItem.kt
app/src/main/java/com/example/ruok_workers/DetailsFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/ListAdapter.kt
app/src/main/java/com/example/ruok_workers/ListCard.kt
app/src/main/java/com/example/ruok_workers/ListFragment.kt
app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/res/layout/fragment_details.xml
app/src/main/res/layout/fragment_list.xml
app/src/main/res/layout/list_items.xml
app/src/main/res/values/list_spinner.xml

상담내역 작성 데이터 DB에 저장하는 코드 구현했습니다!
위치정보 저장은 아직 구현하지 않았습니다

상담내역 데이터 저장 구현-위치정보 저장 제외

---

app/src/main/java/com/example/ruok_workers/HomelessRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/java/com/example/ruok_workers/LocationRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/RevisionFragment.kt
app/src/main/res/layout/fragment_homeless_revision.xml

상담내역 수정 최종 UPDATE 까지 구현 완료

---

app/src/main/java/com/example/ruok_workers/CountingDetailAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionAdapter.kt
app/src/main/java/com/example/ruok_workers/CountingRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/CountingTableFragment.kt
app/src/main/res/layout/fragment_counting_revision.xml

counting 수정

---

app/src/main/java/com/example/ruok_workers/DashboardFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/LocationAddFragment.kt
app/src/main/java/com/example/ruok_workers/LocationRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/SearchFragment.kt

위치 추가, 수정에서도 권한 오류 없앰
search, homelesslist getColumnIndex 에러 해결 (h.h_num 쓰면 로그 뜨길래... 기능 변화 없음)

위치 추가, 수정에서도 권한 오류 없애고 search, homelesslist getColumnIndex 수정

---

app/src/main/java/com/example/ruok_workers/UnknownHomelessFragment.kt

unknown filtering

---

app/src/main/java/com/example/ruok_workers/HomelessListAdapter.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessRevisionFragment.kt

1. 상담내역 작성에서 노숙인 선택 시 노숙인 번호 반영되도록 수정
2. 상담내역 수정 시에서도 같은 문제 해결

상담내역 작성 및 수정 시 노숙인 선택 오류 해결

---

app/src/main/java/com/example/ruok_workers/ConsultationPhotoAdapter.kt
app/src/main/java/com/example/ruok_workers/DetailsFragment.kt
app/src/main/java/com/example/ruok_workers/PhotoRevisionFragment.kt
app/src/main/res/layout/consultation_photo_items.xml
app/src/main/res/layout/fragment_details.xml

1. 상담내역 상세에서 사진 보이도록 구현
2. 상담내역 수정에서 내부저장소에 있는 사진과 drawable에 있는 사진 모두 뜨도록 구현

상담내역 상세 및 수정 사진 렌더링 문제 해결

---

app/src/main/java/com/example/ruok_workers/FaviconAdapter.kt
app/src/main/java/com/example/ruok_workers/FaviconItem.kt
app/src/main/java/com/example/ruok_workers/HomelessListAdapter.kt
app/src/main/java/com/example/ruok_workers/HomelessListFragment.kt
app/src/main/java/com/example/ruok_workers/HomelessRevisionFragment.kt
app/src/main/java/com/example/ruok_workers/SearchFragment.kt

즐겨찾기 DB 연동 구현하였습니다!
HomelessListFragment
HomelessRevisionFragment
SearchFragment
에서 작동하는 것 모두 확인했습니다~!

즐겨찾기 DB 연동

---

app/src/main/java/com/example/ruok_workers/HomelessRevisionFragment.kt

HomelessRevisionFragment에서 노숙인 번호 넘겨주는 부분 한 줄 수정했습니다!

상담내역 수정 시 항상 이름을알수없는노숙인으로 들어가는 문제 해결

---

app/src/main/java/com/example/ruok_workers/BriefingAddFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingAfterFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingBoardFragment.kt

BrefingAfterFragment와 BriefingBoardFragment 수정 하였습니다!

BriefingAfter 게시판 기존 데이터 불러오기 구현

---

app/src/main/java/com/example/ruok_workers/BriefingDetailFragment.kt

브리핑 게시판 글 삭제 시 깨지는 부분 해결하였습니다!

Briefing Delete Debugging

---

app/src/main/java/com/example/ruok_workers/BriefingAfterAdapter.kt
app/src/main/java/com/example/ruok_workers/BriefingAfterFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingBeforeAdapter.kt
app/src/main/java/com/example/ruok_workers/BriefingBoardFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingDetailFragment.kt
app/src/main/java/com/example/ruok_workers/BriefingDuringAdapter.kt
app/src/main/java/com/example/ruok_workers/BriefingDuringFragment.kt
app/src/main/res/layout/briefing_after_item.xml
app/src/main/res/layout/briefing_during_item.xml
app/src/main/res/layout/briefing_item.xml

BriefingAfter와 BriefingDuring에서도 공지가 구별되어 보이도록 수정했습니다!

브리핑 목록 After와 During에서도 공지 뜨도록 구현

---

.idea/deploymentTargetSelector.xml
app/src/main/java/com/example/ruok_workers/ProfileAddFragment.kt
app/src/main/java/com/example/ruok_workers/ProfileDetailFragment.kt
app/src/main/java/com/example/ruok_workers/ProfileRevisionFragment.kt
app/src/main/res/layout/fragment_details.xml
app/src/main/res/layout/fragment_profile_add.xml
app/src/main/res/layout/fragment_profile_detail.xml
app/src/main/res/layout/fragment_profile_revision.xml

프로필 백버튼 막기
프로필 특이사항 xml 및 기능 구현 완료
상담내역 상세보기 스크롤뷰 추가하여 강ㅇ성 ui 붕괴 해결

프로필 특이사항 추가 및 상담내역 스크롤뷰 추가

---

app/src/main/java/com/example/ruok_workers/ListFragment.kt

날짜 필터링 오류 수정
